### ISSUE TITLE
Peer dep issues with React 18

### ISSUE THREAD

**Issue by chamois-d-or** [prismicio/slice-machine#1034] opened 2023-07-06 14:13 UTC
### Versions

- slice-machine-ui: 1.4.0
- node: 18.15.0

### Reproduction

do npm i with react 18.2.0 in deps

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

npm i
when react 18.2.0 in package.json

### What is expected?
everything is ok, install goes by

### What is actually happening?

a lot of warnings pop up

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/menu-button@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/menu-button@0.18.0
npm WARN node_modules/@reach/menu-button
npm WARN   @reach/menu-button@"^0.18.0" from slice-machine-ui@1.4.0
npm WARN   node_modules/slice-machine-ui
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN     @reach/menu-button@"^0.18.0" from slice-machine-ui@1.4.0
npm WARN     node_modules/slice-machine-ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/menu-button@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/menu-button@0.18.0
npm WARN node_modules/@reach/menu-button
npm WARN   @reach/menu-button@"^0.18.0" from slice-machine-ui@1.4.0
npm WARN   node_modules/slice-machine-ui
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN     @reach/menu-button@"^0.18.0" from slice-machine-ui@1.4.0
npm WARN     node_modules/slice-machine-ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/dropdown@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/dropdown@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN   @reach/dropdown@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN     @reach/dropdown@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/dropdown@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/dropdown@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN   @reach/dropdown@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN     @reach/dropdown@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/polymorphic@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/polymorphic@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/polymorphic
npm WARN   @reach/polymorphic@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN   2 more (@reach/dropdown, @reach/popover)
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/polymorphic@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/polymorphic
npm WARN     @reach/polymorphic@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN     2 more (@reach/dropdown, @reach/popover)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/popover@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/popover@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN   @reach/popover@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN   1 more (@reach/dropdown)
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN     @reach/popover@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN     1 more (@reach/dropdown)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/popover@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/popover@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN   @reach/popover@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN   1 more (@reach/dropdown)
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN     @reach/popover@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN     1 more (@reach/dropdown)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/utils@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/utils@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/utils
npm WARN   @reach/utils@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN   6 more (@reach/dropdown, @reach/auto-id, @reach/descendants, ...)
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/utils@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/utils
npm WARN     @reach/utils@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN     6 more (@reach/dropdown, @reach/auto-id, @reach/descendants, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/utils@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/utils@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/utils
npm WARN   @reach/utils@"0.18.0" from @reach/menu-button@0.18.0
npm WARN   node_modules/@reach/menu-button
npm WARN   6 more (@reach/dropdown, @reach/auto-id, @reach/descendants, ...)
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/utils@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/utils
npm WARN     @reach/utils@"0.18.0" from @reach/menu-button@0.18.0
npm WARN     node_modules/@reach/menu-button
npm WARN     6 more (@reach/dropdown, @reach/auto-id, @reach/descendants, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: connected-next-router@4.2.0
npm WARN Found: react-redux@8.0.7
npm WARN node_modules/react-redux
npm WARN   react-redux@"8.0.7" from slice-machine-ui@1.4.0
npm WARN   node_modules/slice-machine-ui
npm WARN     dev slice-machine-ui@"^1.4.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-redux@"^7.1.0" from connected-next-router@4.2.0
npm WARN node_modules/slice-machine-ui/node_modules/connected-next-router
npm WARN   connected-next-router@"^4.2.0" from slice-machine-ui@1.4.0
npm WARN   node_modules/slice-machine-ui
npm WARN 
npm WARN Conflicting peer dependency: react-redux@7.2.9
npm WARN node_modules/react-redux
npm WARN   peer react-redux@"^7.1.0" from connected-next-router@4.2.0
npm WARN   node_modules/slice-machine-ui/node_modules/connected-next-router
npm WARN     connected-next-router@"^4.2.0" from slice-machine-ui@1.4.0
npm WARN     node_modules/slice-machine-ui
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/auto-id@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/auto-id@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/auto-id
npm WARN   @reach/auto-id@"0.18.0" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/auto-id@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/auto-id
npm WARN     @reach/auto-id@"0.18.0" from @reach/dropdown@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/auto-id@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/auto-id@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/auto-id
npm WARN   @reach/auto-id@"0.18.0" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/auto-id@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/auto-id
npm WARN     @reach/auto-id@"0.18.0" from @reach/dropdown@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/descendants@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/descendants@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/descendants
npm WARN   @reach/descendants@"0.18.0" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/descendants@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/descendants
npm WARN     @reach/descendants@"0.18.0" from @reach/dropdown@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/descendants@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/descendants@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/descendants
npm WARN   @reach/descendants@"0.18.0" from @reach/dropdown@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/descendants@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/dropdown/node_modules/@reach/descendants
npm WARN     @reach/descendants@"0.18.0" from @reach/dropdown@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/dropdown
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/portal@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/portal@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/portal
npm WARN   @reach/portal@"0.18.0" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/portal@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/portal
npm WARN     @reach/portal@"0.18.0" from @reach/popover@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/portal@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/portal@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/portal
npm WARN   @reach/portal@"0.18.0" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/portal@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/portal
npm WARN     @reach/portal@"0.18.0" from @reach/popover@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/rect@0.18.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   134 more (@emotion/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from @reach/rect@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/rect
npm WARN   @reach/rect@"0.18.0" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || 17.x" from @reach/rect@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/rect
npm WARN     @reach/rect@"0.18.0" from @reach/popover@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/rect@0.18.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   52 more (@floating-ui/react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from @reach/rect@0.18.0
npm WARN node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/rect
npm WARN   @reach/rect@"0.18.0" from @reach/popover@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.8.0 || 17.x" from @reach/rect@0.18.0
npm WARN   node_modules/@reach/menu-button/node_modules/@reach/popover/node_modules/@reach/rect
npm WARN     @reach/rect@"0.18.0" from @reach/popover@0.18.0
npm WARN     node_modules/@reach/menu-button/node_modules/@reach/popover

**Comment by xrutayisire** [comment] 2023-07-06 14:47
Hey,

Thanks for the report, we have an issue since the 1.4.0 with dependencies that can happen. We will provide a fix in a next release. Not the one that will be released today, but right after.

In the meantime, this issue is already tracked under: https://github.com/prismicio/slice-machine/issues/1026 so I close this one even if the output is different the root cause is the same, and we will try to centralize everything in the other issue.

**Closed as completed by xrutayisire** 2023-07-06 14:47 UTC
Labels: bug
