### ISSUE TITLE
Nuxt 3: When navigating through pages that contain only one and same slice, the slice flashes the previous data for a millisecond

### ISSUE THREAD

**Issue by Liam-hi** [prismicio/slice-machine#1104] opened 2023-08-15 20:03 UTC
### Versions

- slice-machine-ui: 1.8.0
- node: 18.17.3

### Reproduction

The Nuxt 3 starter [Clean Blog](https://nuxt-starter-prismic-blog.vercel.app/) display the same content when clicking on the blog posts. Therefore, I created a working version to illustrate the issue.

[Clean Blog in Nuxt 3](https://lalalala-two.vercel.app/).

Second example: 

[Simple navigation](https://second-example.vercel.app/)

[Simple navigation - repo](https://github.com/Liam-hi/second-example)

### Steps to reproduce

Click on the blog posts. 

Second example: click on the links.

### What is expected?

See the Next.js version: [Clean Blog in Next.js](https://nextjs-starter-prismic-blog.vercel.app/).

The Slice renders smoothly, without displaying previous data or causing HTML elements to jump.

https://github.com/prismicio/slice-machine/assets/74251943/7f76d719-30a2-4c92-9731-54253a6c40d5

Second example created in Next.js instead. No flashes at all. 

https://github.com/prismicio/slice-machine/assets/74251943/3f5ee3c2-188c-400a-a432-ad9253d8258a

[Second example](https://third-example.vercel.app/)

[Link to repo](https://github.com/Liam-hi/third-example)

### What is actually happening?

In Nuxt 3, when clicking on the blog posts, you see the previous data before the new one is rendered. This causes HTML elements to jump, resulting in a visually unpleasant user experience.

https://github.com/prismicio/slice-machine/assets/74251943/53939ef3-17a0-491b-a103-77f33a24689e

Second example: 

https://github.com/prismicio/slice-machine/assets/74251943/69ed2262-121d-49b7-901e-1ca100a7e8ce

**Comment by mdeclercq** [comment] 2023-09-15 13:56
Hi @Liam-hi,

Thanks a lot for reporting the issue and providing all the details to reproduce. It really helps!

The issue is now fixed on the [blog demo site](https://nuxt-starter-prismic-blog.vercel.app/). 
This change fixed both issues you reported: https://github.com/prismicio-community/nuxt-starter-prismic-blog/pull/46
1. articles content not refreshing while navigating -> this was reproducible when running `npm run generate`
2. previous article content flashing for a millisecond -> this was reproducible when running `npm run build`

You can apply a similar fix on your own project to fix it.

I'm closing the issue, let us know if you still encounter an issue and we'll reopen it.
Thanks,

**Closed as completed by mdeclercq** 2023-09-15 13:56 UTC
Labels: bug
